package snakeandladder;

import java.util.Random;

public class SnakeAndLadder {
	public static void main(String[] args) {
		int startPosition = 0;
		int noPlay = 1;
		int ladder = 2;
		Random random = new Random();
		while (startPosition < 100) {
			int condition = random.nextInt(4 - 1) + 1;
			int dice = random.nextInt(7 - 1) + 1;
			System.out.println("Random number generated by dice is :" + " " + dice);
			if (condition == noPlay) {
				System.out.println("You got No-Play Option!");
			} else if (condition == ladder) {
				System.out.println("You got Ladder!");
				startPosition += dice;
				if (startPosition > 100) {
					startPosition -= dice;
				}
			} else {
				System.out.println("You got Snake!");
				startPosition -= dice;
				if (startPosition < 0) {
					startPosition = 0;
				}
			}
			System.out.println("Curruent position of player is :" + " " + startPosition);
		}
	}
}